### ISSUE TITLE
 java.lang.NullPointerException

### ISSUE THREAD

**Issue by xiaoer521** [elemers/HermesEventBus#31]
接入后，一直在报NullPointerException
1.xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.void onHermesConnected(java.lang.Class)(SourceFile:291)
 xiaofei.library.hermes.internal.Channel$HermesServiceConnection.void onServiceConnected(android.content.ComponentName,android.os.IBinder)(SourceFile:288)
2.Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.a.a(int, xiaofei.library.hermeseventbus.b)' on a null object reference

**Comment by xiaoer521** [comment]
希望帮忙看一下，报错很严重，谢谢啦

**Comment by Xiaofei-it** [comment]
1、用法好像有问题。

2、把我的库全部keep了再试试看。
