### ISSUE TITLE
我提几个建议

### ISSUE THREAD

**Issue by LuckyJayce** [elemers/HermesEventBus#34]
1.  EventBus不太适合用Hermes，因为EventBus只调用方法不需要返回值以及等待返回，aidl声明有个oneway关键字，执行aidl方法时候是不阻塞调用    
  
2.  绑定服务的时机，关于作者开一个服务，多个进程同时去通过aidl绑定这个服务发布事件这点非常好，但是绑定服务不应该是在init时候，而是在子进程发布事件，子进程注册事件的时候判断有没有绑定服务，没有连接就去绑定  
  
3.  发布事件，目前是发布一个跨进程的事件所有进程都接收，我觉得没有必要所有进程接收，post远程事件的时候多个processName的参数，发布事件到指定的进程。
    
4.  EventBus用多了就乱，我觉得以接口的方式定义event，接收者实现这个接口，发布者通过这个接口发布事件，目前我实现了两种方式一种是动态代理自动实现使用者定义的接口，一种是apt的方式自动那个实现使用者定义的接口。  

以上是个人建议，总的来说开一个服务，多个进程同时去通过aidl绑定这个服务发布事件这点想法很好

**Comment by Xiaofei-it** [comment]
谢谢你的建议。

1. 为了简化模型，所以并没有使用oneway方式。况且我用的是Hermes库，没有提供oneway的支持。另外，取sticky事件的时候需要读取返回值。我觉得一方面要返回值，另一方面又不要返回值。如果对两个情况分开处理，太麻烦。所以当时没想这么多。不过你这个建议非常好，那就要对Hermes库进行修改，增加不需要返回值的接口。

2. 连接服务是需要时间的，所以如果延迟这个连接的时机，一方面会造成事件发送的延后，另一方面也增加编程复杂性。所以我并不想这么做。

3. 这个是我对EventBus的理解，因为这个库发出的事件是全局能收到的，所以我就觉得没必要指定进程。

4. 具体可以给我看看你的项目，我可以借鉴一下。

另外，我当时写这个库，是基于一个非常简单的模型，就是传统的C-S模式。里面肯定会有一些地方是当时为了实现方便而没有考虑性能，但我觉得这些消耗都比较小，所以可以不考虑。举个例子：每次子进程发事件的时候，可以先在自己内部发事件，然后发给main process，main process向外发送事件的时候其实不必再发给之前那个进程了。但我当时为了实现方便，没有这么做，而是子进程直接发给main process，由main process回发给子进程。

**Comment by LuckyJayce** [comment]
@Xiaofei-it 我写的https://github.com/LuckyJayce/EventBus-Apt 下的 feature/eventproxy 分支，
还没测试完用例，没提交到mater分支  
另外一个https://github.com/LuckyJayce/EventBus  是动态代理版的，等apt版的写好再更新

**Comment by Xiaofei-it** [comment]
好的，谢谢！
